sudo: required
services:
  - docker
language: scala
scala:
- 2.12.4
script:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- sbt ++$TRAVIS_SCALA_VERSION docker:publish
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
#  - $HOME/.coursier
